inherit_mode:
  merge:
    - Exclude

plugins:
  - standard-custom

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml

inherit_from:
  - .rubocop/rubocop_rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'bench/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 3.2

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
